import os
import re
from typing import List, Any
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute and print 'Page X of Y' page numbers.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_elements(num_pages)
            super().showPage()
        super().save()

    def draw_page_elements(self, page_count):
        self.saveState()
        
        # Suppress headers/footers on page 1 (cover page)
        if self._pageNumber > 1:
            # Header
            self.setFont("Helvetica", 8)
            self.setFillColor(colors.HexColor("#64748b"))
            self.drawString(54, 750, "ResearchPilot — Autonomous Academic Assistant")
            self.setStrokeColor(colors.HexColor("#cbd5e1"))
            self.setLineWidth(0.5)
            self.line(54, 742, 612 - 54, 742)
            
            # Footer
            self.setFont("Helvetica", 9)
            page_text = f"Page {self._pageNumber} of {page_count}"
            self.drawRightString(612 - 54, 36, page_text)
            self.drawString(54, 36, "Confidential & Proprietary — Generated by ResearchPilot")
            self.line(54, 48, 612 - 54, 48)
            
        self.restoreState()


class ReportService:
    def __init__(self, output_dir: str = "backend/reports"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_pdf(self, markdown_text: str, filename: str) -> str:
        """
        Compile professional PDF from markdown report.
        """
        pdf_path = os.path.join(self.output_dir, filename)
        doc = SimpleDocTemplate(
            pdf_path,
            pagesize=letter,
            rightMargin=54,
            leftMargin=54,
            topMargin=72,
            bottomMargin=72
        )
        
        # Setup modern stylesheets
        styles = getSampleStyleSheet()
        
        # Define clean, beautiful typography & palette
        primary_color = colors.HexColor("#1e293b")  # Dark Slate Blue
        secondary_color = colors.HexColor("#0f766e")  # Teal
        text_color = colors.HexColor("#334155")  # Dark Grey
        accent_color = colors.HexColor("#2563eb")  # Blue
        
        title_style = ParagraphStyle(
            'CoverTitle',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=28,
            leading=34,
            textColor=primary_color,
            spaceAfter=15,
            alignment=0  # Left aligned
        )
        
        subtitle_style = ParagraphStyle(
            'CoverSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=14,
            leading=18,
            textColor=secondary_color,
            spaceAfter=40
        )
        
        metadata_style = ParagraphStyle(
            'CoverMetadata',
            parent=styles['Normal'],
            fontName='Helvetica-Oblique',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#64748b"),
        )
        
        h1_style = ParagraphStyle(
            'CustomH1',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=18,
            leading=22,
            textColor=primary_color,
            spaceBefore=22,
            spaceAfter=10,
            keepWithNext=True
        )
        
        h2_style = ParagraphStyle(
            'CustomH2',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=13,
            leading=17,
            textColor=secondary_color,
            spaceBefore=14,
            spaceAfter=6,
            keepWithNext=True
        )
        
        h3_style = ParagraphStyle(
            'CustomH3',
            parent=styles['Heading3'],
            fontName='Helvetica-Bold',
            fontSize=11,
            leading=15,
            textColor=accent_color,
            spaceBefore=10,
            spaceAfter=4,
            keepWithNext=True
        )
        
        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=text_color,
            spaceBefore=0,
            spaceAfter=8
        )
        
        list_style = ParagraphStyle(
            'CustomList',
            parent=body_style,
            leftIndent=15,
            firstLineIndent=-10,
            spaceAfter=4
        )

        story = []
        
        # 1. GENERATE COVER PAGE
        story.append(Spacer(1, 100))
        # Abstracted professional title from markdown
        title_match = re.search(r'^#\s+(.+)$', markdown_text, re.MULTILINE)
        report_title = title_match.group(1) if title_match else "LITERATURE SURVEY & RESEARCH ROADMAP"
        
        # Strip the H1 title out of markdown to prevent double printing
        cleaned_markdown = re.sub(r'^#\s+.+$', '', markdown_text, flags=re.MULTILINE)
        
        story.append(Paragraph(report_title.upper(), title_style))
        story.append(Paragraph("Autonomously Synthesized Literature Survey, Critical Review, and Future Research Roadmap", subtitle_style))
        story.append(Spacer(1, 150))
        
        story.append(Paragraph("<b>Prepared by:</b> ResearchPilot AI Multi-Agent Core Engine", metadata_style))
        import datetime
        date_str = datetime.datetime.now().strftime("%B %d, %Y")
        story.append(Paragraph(f"<b>Date:</b> {date_str}", metadata_style))
        story.append(Paragraph("<b>Status:</b> Research Compilation Completed", metadata_style))
        story.append(PageBreak())
        
        # 2. PARSE MARKDOWN TO STORY
        lines = cleaned_markdown.split('\n')
        in_list = False
        in_table = False
        table_data = []
        
        i = 0
        while i < len(lines):
            line = lines[i]
            
            # Table Parsing
            if line.strip().startswith('|'):
                in_table = True
                cells = [c.strip() for c in line.split('|')[1:-1]]
                # Skip the division line like |---|---|
                if not all(c.startswith('-') or c == '' for c in cells):
                    # Format bold content in table headers
                    if len(table_data) == 0:
                        cells = [f"<b>{c}</b>" for c in cells]
                    table_data.append(cells)
                i += 1
                continue
            elif in_table and not line.strip().startswith('|'):
                # Render table
                in_table = False
                if table_data:
                    # Map to Paragraphs to support text wrapping
                    wrapped_data = []
                    for r_idx, row in enumerate(table_data):
                        wrapped_row = []
                        for c_idx, cell in enumerate(row):
                            cell_style = ParagraphStyle(
                                f'TableCell_{r_idx}_{c_idx}',
                                parent=body_style,
                                fontSize=8.5,
                                leading=11,
                                spaceAfter=0
                            )
                            wrapped_row.append(Paragraph(cell, cell_style))
                        wrapped_data.append(wrapped_row)
                        
                    col_width = (612 - 108) / len(table_data[0]) # Equal width columns
                    t = Table(wrapped_data, colWidths=[col_width]*len(table_data[0]))
                    t.setStyle(TableStyle([
                        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#f1f5f9")),
                        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                        ('VALIGN', (0,0), (-1,-1), 'TOP'),
                        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
                        ('TOPPADDING', (0,0), (-1,-1), 8),
                        ('LEFTPADDING', (0,0), (-1,-1), 6),
                        ('RIGHTPADDING', (0,0), (-1,-1), 6),
                        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#f8fafc")]),
                        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
                    ]))
                    story.append(t)
                    story.append(Spacer(1, 10))
                    table_data = []
            
            # Header 1
            h1_match = re.match(r'^##\s+(.+)$', line)
            if h1_match:
                title = h1_match.group(1)
                story.append(Paragraph(title, h1_style))
                i += 1
                continue
                
            # Header 2
            h2_match = re.match(r'^###\s+(.+)$', line)
            if h2_match:
                title = h2_match.group(1)
                story.append(Paragraph(title, h2_style))
                i += 1
                continue
                
            # Header 3
            h3_match = re.match(r'^####\s+(.+)$', line)
            if h3_match:
                title = h3_match.group(1)
                story.append(Paragraph(title, h3_style))
                i += 1
                continue
                
            # Unordered lists
            list_match = re.match(r'^\s*[-*]\s+(.+)$', line)
            if list_match:
                content = list_match.group(1)
                # Formulate bold starts
                content = re.sub(r'^\*\*(.*?)\*\*:', r'<b>\1</b>:', content)
                story.append(Paragraph(f"&bull; {content}", list_style))
                i += 1
                continue
                
            # Standard Text
            text = line.strip()
            if text:
                # Format bold text
                text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', text)
                text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', text)
                story.append(Paragraph(text, body_style))
                story.append(Spacer(1, 4))
                
            i += 1
            
        doc.build(story, canvasmaker=NumberedCanvas)
        print(f"Beautiful PDF report compiled at: {pdf_path}")
        return pdf_path
